version: '3.8'

services:
  # PostgreSQL 資料庫
  postgres:
    image: postgres:15-alpine
    container_name: fsvs-postgres
    environment:
      POSTGRES_DB: foreign_student_verification
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=C.UTF-8 --lc-ctype=C.UTF-8"
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - fsvs-network
    command: postgres -c client_encoding=UTF8

  # Redis 快取
  redis:
    image: redis:7-alpine
    container_name: fsvs-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - fsvs-network

  # MinIO 檔案儲存 (S3 相容)
  minio:
    image: minio/minio:latest
    container_name: fsvs-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - fsvs-network

  # 後端 API (開發環境)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: fsvs-backend
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: foreign_student_verification
      DB_USER: postgres
      DB_PASSWORD: password
      REDIS_HOST: redis
      REDIS_PORT: 6379
      AWS_ENDPOINT: http://minio:9000
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin123
      AWS_S3_BUCKET: foreign-student-docs
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - postgres
      - redis
      - minio
    networks:
      - fsvs-network

  # 前端應用 (開發環境)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: fsvs-frontend
    environment:
      VITE_API_URL: http://localhost:5001/api
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - fsvs-network

volumes:
  postgres_data:
  redis_data:
  minio_data:

networks:
  fsvs-network:
    driver: bridge