name: ogastudent-verification-system
region: sfo3

# 使用最便宜的方案進行測試
services:
  - name: backend
    source_dir: /backend
    github:
      repo: tzustu63/ogastudent
      branch: main
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs # 最便宜的方案
    http_port: 5000
    routes:
      - path: /api
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "5000"
      - key: JWT_SECRET
        value: "your-super-secret-jwt-key-for-testing-please-change-in-production"
      - key: JWT_EXPIRES_IN
        value: "24h"
      - key: DB_HOST
        value: ${postgres-db.HOSTNAME}
      - key: DB_PORT
        value: ${postgres-db.PORT}
      - key: DB_NAME
        value: ${postgres-db.DATABASE}
      - key: DB_USER
        value: ${postgres-db.USER}
      - key: DB_PASSWORD
        value: ${postgres-db.PASSWORD}
      - key: CORS_ORIGIN
        value: ${frontend.URL}
      - key: LOG_LEVEL
        value: "info"
      # Redis 相關環境變數設為空，讓應用程式使用記憶體快取
      - key: REDIS_HOST
        value: ""
      - key: REDIS_PORT
        value: ""
      - key: REDIS_PASSWORD
        value: ""

  - name: frontend
    source_dir: /frontend
    github:
      repo: tzustu63/ogastudent
      branch: main
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs # 最便宜的方案
    http_port: 8080
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: ${backend.URL}/api
      - key: PORT
        value: "8080"

# 資料庫配置 - 只使用 PostgreSQL
databases:
  - name: postgres-db
    engine: PG
    version: "15"
    size: db-s-1vcpu-1gb # 最便宜的資料庫方案
    num_nodes: 1
